name: card_wizz
description: A digital business card management application
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Add these new dependencies
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  fl_chart: ^0.65.0
  lottie: ^2.7.0
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.5
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  flutter_contacts: ^1.1.7
  qr_flutter: ^4.1.0
  share_plus: ^7.1.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0
  path: ^1.8.3
  characters: ^1.3.0  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/names.json
    - assets/avatars/    # Add this line
