name: cardwizz
description: A TCG card collection management app
version: 1.0.0+1  # Make sure this matches your App Store version

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.0
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  fl_chart: ^0.65.0
  lottie: ^2.7.0
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.5
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  flutter_contacts: ^1.1.7
  qr_flutter: ^4.1.0
  share_plus: ^7.1.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0
  path: ^1.8.3
  characters: ^1.3.0
  shimmer: ^3.0.0  # Add this line
  intl: ^0.19.0  # Update this line from ^0.18.0 to ^0.19.0
  in_app_purchase: ^3.1.11
  uni_links: ^0.5.1
  workmanager: ^0.5.2
  background_fetch: ^1.2.1
  cached_network_image: ^3.3.0
  dio: ^5.3.3  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
  
  assets:
    - assets/animations/
    - assets/names.json
    - assets/avatars/    # Add this line
    - assets/animations/background.json
    - assets/animations/SplashAnimation.json  # Add this specific file
    - assets/animations/Loading.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  android: false
  ios: false

  # Removed all other configurations to keep it simple
