name: cardwizz
description: A card collection management app.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Core functionality
  sqflite: ^2.3.0
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  path: ^1.8.3
  intl: ^0.19.0  # Updated to match flutter_localizations requirement
  rxdart: ^0.27.7
  
  # UI components
  fl_chart: ^0.63.0
  shimmer: ^3.0.0 
  lottie: ^2.6.0
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2
  
  # Network and API
  dio: ^5.3.0
  connectivity_plus: ^5.0.0
  
  # Image handling
  image_picker: ^1.0.1
  flutter_cache_manager: ^3.3.1
  palette_generator: ^0.3.3+2
  cached_network_image: ^3.2.3
  
  # Authentication
  sign_in_with_apple: ^5.0.0
  google_sign_in: ^6.1.5
  
  # Device functionality
  camera: ^0.10.5+2
  permission_handler: ^11.0.0
  background_fetch: ^1.2.1
  workmanager: ^0.5.1
  flutter_secure_storage: ^8.0.0
  uni_links: ^0.5.1
  share_plus: ^7.1.0
  flutter_contacts: ^1.1.7+1
  # Temporarily comment out problematic package
  # cloud_kit: ^2.0.0
  url_launcher: ^6.1.12
  
  # Barcode scanning
  google_mlkit_text_recognition: ^0.8.1
  
  # UI components
  qr_flutter: ^4.1.0
  
  # In-app purchases
  in_app_purchase: ^3.1.10
  
  # Additional utilities
  yaml: ^3.1.2

# Update dependency overrides to resolve CocoaPods conflict
dependency_overrides:
  google_sign_in_ios: 5.5.0  # Use an older version that doesn't require GTMSessionFetcher 3.4.0+
  google_mlkit_text_recognition: 0.5.0
  google_mlkit_commons: 0.2.0
  camera: 0.10.5
  # Fixed version combination for Google Sign In to work together
  google_sign_in: 6.0.2
  google_sign_in_platform_interface: 2.2.0
  google_sign_in_web: 0.10.2
  # Add this to fix the error with forceAccountName parameter
  google_sign_in_android: 6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dependency_validator: ^5.0.2
  # Move these to dev_dependencies as suggested by dependency_validator
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1
  # Remove path from dev dependencies as it's already in regular dependencies
  
# Configurations for flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/avatars/
    # Remove or create these directories
    # - assets/lottie/
    # - assets/logos/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
