name: cardwizz
description: A TCG card collection management app
version: 1.0.0+1  # Verify this matches your app store versions

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  collection: ^1.17.0
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  provider: ^6.0.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  fl_chart: ^0.65.0
  lottie: ^2.7.0
  url_launcher: ^6.2.1
  cupertino_icons: ^1.0.5
  path_provider: ^2.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  flutter_contacts: ^1.1.7
  qr_flutter: ^4.1.0
  share_plus: ^7.1.0
  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  sqflite: ^2.3.0
  path: ^1.8.3
  characters: ^1.3.0
  shimmer: ^3.0.0  # Add this line
  intl: ^0.19.0  # Update this line from ^0.18.0 to ^0.19.0
  in_app_purchase: ^3.1.11
  revenue_cat_flutter: ^6.3.0  # Optional but recommended for subscription management

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/names.json
    - assets/avatars/    # Add this line
    - assets/animations/background.json
